# Generated by Django 4.2.7 on 2023-12-09 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippingAdress",
            new_name="ShippingAddress",
        ),
    ]
