# Generated by Django 4.2.7 on 2023-12-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_rename_adress_shippingaddress_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
